version: '3.7'
services:
  redis6001:
    image: redis:7.0.9
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    restart: always
    volumes:
      - /mnt/c/_DEV/redis-7.0.9:/data
      - /mnt/c/_DEV/redis-7.0.9/conf:/data/conf
      - /mnt/c/_DEV/redis-7.0.9/conf/redis.conf:/data/conf/redis.conf
    command: redis-server /data/conf/redis.conf