# 상품 추가
POST /products HTTP/1.1
Content-Type: application/json
Host: demo.com

{
  "name" : "노랑 니트",
  "stockQuantity" : 5,
  "price" : 1000,
  "categoryInfo": {
    "id": 2,
    "catName": "니트",
    "status": "ACTIVE",
    "catLevel": 2,
    "upperCatCode": 1
  }
}

###
# 조회 > 개별상품 []
GET /products/1 HTTP/1.1
Host: demo.com


###
# 조회 > 상품 검색
GET /products?upperCatCode=1 HTTP/1.1
Host: demo.com

###
# 상품 수정
PUT /products/1
Host: demo.com
Content-Type: application/json

{
  "name" : "노랑 니트",
  "stockQuantity" : 6,
  "price" : 1000,
  "categoryInfo": {
    "id": 2,
    "catName": "니트",
    "status": "ACTIVE",
    "catLevel": 2,
    "upperCatCode": 1
  }
}
###
# 상품 삭제
DELETE /products/3 HTTP/1.1
Host: demo.com
