###################
# local
###################
server.port: 18080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/commerce;MODE=MYSQL
    username: sa
    password:
  #### jpa ###
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
  #### cache ###
  cache:
    type: redis
    ttl: 36288000
  #### redis ###
  redis:
    cache:
      host: host.docker.internal
      port: 6001

#### logging ###
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
