###################
# local
###################
server.port: 18080

spring:
  #### h2 ###
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/sample;MODE=MYSQL
    username: sa
    password:
  #### jpa ###
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
  ##### REDIS ####
  cache:
    type: redis
  #### redis ###
  redis:
    cache:
      host: host.docker.internal
      port: 6001



#### logging ###
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
