###################
# test
###################
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/commerce;MODE=MYSQL
    username: sa
    password:
  #### jpa ###
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true

