###################
# local
###################
server.port: 18080

spring:
# ----------------------
# dataSource
# ----------------------
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/sample;MODE=MYSQL
    username: sa
    password:
# ----------------------
# jpa
# ----------------------
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
# ----------------------
# REDIS
# ----------------------
  redis:
    host: host.docker.internal
    port: 6001