###################
# local
###################
server.port: 18080

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/commerce;MODE=MYSQL
#    username: sa
#    password:
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://192.168.0.9:3306/sample
      driver-class-name: org.mariadb.jdbc.Driver
      username: sample
      password: sample1234
  #### jpa ###
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
  #### cache ###
  cache:
    type: redis
  #### redis ###
  redis:
    cache:
      host: host.docker.internal
      port: 6001

